Basically provides the automatic differentitation for tensor operations. thus it enables gradient calculations

In [3]:
import torch

In [4]:
x= torch.tensor(3.0,requires_grad=True)   #set to True if I want gradient at any point(makes a computation graph)
y=x**2
y

tensor(9., grad_fn=<PowBackward0>)

In [5]:
y.backward()   #creates all the gradients in chain rule

In [6]:
x.grad   #Not clear why need to do x.grad instead of y.grad(which is intuitive)

tensor(6.)

In [7]:
x=torch.tensor(30.0,requires_grad=True) # Re-initialize x for a fresh graph, since each time I call backward function it consumes the computational graph
y=x**2 #Re-initialize y
z=torch.sin(y)
print(z)
print(y)
print(x)
z.backward() # This will now correctly compute dz/dx and store it in x.grad
x.grad

tensor(0.9978, grad_fn=<SinBackward0>)
tensor(900., grad_fn=<PowBackward0>)
tensor(30., requires_grad=True)


tensor(3.9748)

Applying this to do back propagation in a simple perceptron. With cross-entropy loss

In [26]:
x=torch.tensor(7.4) #input
y=torch.tensor(0.0) #true-label
w=torch.tensor(1.0,requires_grad=True) #weight
b=torch.tensor(0.0,requires_grad=True) #bias


In [27]:
#binary cross-entropy for scalar
def binary_cross_entropy(y_pred,y_true):
    epsilon=1e-8 #to prevent log(0)
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)  #keeping the predicted value in a given range
    return -(y_true*torch.log(y_pred)+(1-y_true)*torch.log(1-y_pred))

In [28]:
#forward pass
z=w*x+b
y_pred=torch.sigmoid(z)
loss=binary_cross_entropy(y_pred,y)
print(loss)


tensor(7.4005, grad_fn=<NegBackward0>)


In [29]:
loss.backward()
print(w.grad)
print(b.grad)

tensor(7.3955)
tensor(0.9994)


In [43]:
x1=torch.tensor([1.0,2.0,3.0],requires_grad=True)
y1=(x1**2).mean()
print(x1)
print(y1)
y1.backward()
x1.grad

tensor([1., 2., 3.], requires_grad=True)
tensor(4.6667, grad_fn=<MeanBackward0>)


tensor([0.6667, 1.3333, 2.0000])

Clearing gradient

In [44]:
x1.grad.zero_()

tensor([0., 0., 0.])

Disable gradient tracking

In [46]:
x.requires_grad_(False)
y=x**2
y

tensor(54.7600)

In [51]:
#another way
x=torch.tensor([3.0],requires_grad=True)
z=x.detach()
print(z)
y=x**2
print(y)
y2=z**2
y2
y.backward()
y1.backward()

tensor([3.])
tensor([9.], grad_fn=<PowBackward0>)


RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [52]:
with torch.no_grad():
  y=x**2
y

tensor([9.])