In [1]:
import torch
import torch.nn as nn


In [13]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1=nn.Linear(num_features,3)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()
  #forforward-pass
  def forward(self,features):
    out=self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)
    return out



In [14]:
#create dataset
features=torch.rand(10,5)
#model
model=Model(features.shape[1])
#forward pass
model(features)

tensor([[0.3987],
        [0.4016],
        [0.3937],
        [0.4016],
        [0.3967],
        [0.3967],
        [0.4016],
        [0.4014],
        [0.3943],
        [0.4016]], grad_fn=<SigmoidBackward0>)

In [20]:
#show weights
print(model.linear1.weight)
print(model.linear2.weight)

Parameter containing:
tensor([[-0.2112, -0.2534, -0.4447,  0.1408, -0.0493],
        [ 0.3459,  0.3022, -0.3310,  0.4155, -0.3353],
        [-0.0514, -0.1211, -0.3238,  0.3984,  0.0076]], requires_grad=True)
Parameter containing:
tensor([[-0.0496, -0.1731,  0.4699]], requires_grad=True)


In [9]:
!pip install torchinfo


In [21]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00