In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


In [3]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name()}")
else:
  print("GPU is not available")

GPU is available!
Using GPU: Tesla T4


Creating Tensors

In [6]:
#USING empty
a=torch.empty(2,3)   #just allocates the space and shows garbage values


In [8]:
#check type
type(a)

torch.Tensor

In [11]:
#using zeros and ones
torch.zeros(2,3)
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
#using rand
torch.rand(2,3)  #random values of 2x3 dim between 0 to 1


tensor([[0.8390, 0.0602, 0.7711],
        [0.5904, 0.0460, 0.0513]])

In [20]:
#manual seed
torch.manual_seed(50)   #same seed fixes the random values if I run multiple times
torch.rand(2,3)

tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442]])

In [37]:
#custom tensor
x1=torch.tensor([[1,2,3],[4,5,6]])
print(x1)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [26]:
#other
print(torch.arange(0,20,3))
print(torch.linspace(0,10,10))
print(torch.eye(5))
print(torch.full((3,7,3),5))

tensor([ 0,  3,  6,  9, 12, 15, 18])
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5],
         [5, 5, 5],
         [5, 5, 5],
         [5, 5, 5],
         [5, 5, 5]],

        [[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5],
         [5, 5, 5],
         [5, 5, 5],
         [5, 5, 5],
         [5, 5, 5]],

        [[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5],
         [5, 5, 5],
         [5, 5, 5],
         [5, 5, 5],
         [5, 5, 5]]])


Tesnsor Shapes      

In [36]:
x1.shape


torch.Size([2, 3])

In [44]:
#now I can copy the shape of x1 and create another tensor with diff values
y1=torch.empty_like(x1)
y2=torch.zeros_like(x1)
y3=torch.ones_like(x1)
y4=torch.rand_like(x1,dtype=torch.float32)
print(y1)
print(y2)
print(y3)
print(y4)

tensor([[                  0,  244322908328165376,                2420],
        [          208273408,                   0, 1041457413829427200]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0.4985, 0.9987, 0.6049],
        [0.5229, 0.6974, 0.2505]])


Tensor Data Type


In [40]:
#find attribute
x1.dtype

torch.int64

In [41]:
#assign data type
torch.tensor([1.3,2.5,6.9],dtype=torch.int32)

tensor([1, 2, 6], dtype=torch.int32)

In [42]:
#change data type
x1.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Mathematical operations

In [47]:
x2=torch.rand(3,3)
x2

tensor([[0.6907, 0.7526, 0.1184],
        [0.8699, 0.8391, 0.0532],
        [0.1705, 0.2914, 0.5682]])

In [62]:
#addition
x2+2
#multi
x2*3
#subtraction
x2-1
#division
x2/2
#int_division
(x2*100)//3
#mod
((x2*100)//3)%2
#power
x2**2

tensor([[0.4771, 0.5665, 0.0140],
        [0.7567, 0.7041, 0.0028],
        [0.0291, 0.0849, 0.3229]])

Element wise operation


In [74]:
#very similar to Numpy.(skipping)
c=torch.tensor([1,-2,3,4,-5])
#abs
print(torch.abs(c))
#negatve
print(torch.neg(c))
d=torch.tensor([1.9,2.3,4,5.4,6.7])
#round
print(torch.round(d))
#floor
print(torch.floor(d))
#ceil
print(torch.ceil(d))
#clamp-to keep the number in the tnsor in between a range
torch.clamp(d,min=2.2,max=5)


tensor([1, 2, 3, 4, 5])
tensor([-1,  2, -3, -4,  5])
tensor([2., 2., 4., 5., 7.])
tensor([1., 2., 4., 5., 6.])
tensor([2., 3., 4., 6., 7.])


tensor([2.2000, 2.3000, 4.0000, 5.0000, 5.0000])

Reduction operations

In [82]:
e=torch.randint(size=(4,5),low=0,high=10)
print(e)
torch.sum(e)
#colsum
print(torch.sum(e,dim=0))
#rowsum
print(torch.sum(e,dim=1))
#similar for mean,median,max,min,prod,std,var,argmax,argmin
print(torch.argmax(e))  #POSITION OF MAX ITEM, if used without dim then it flattens the tensor and then gives the item number
print(torch.argmin(e))

tensor([[6, 7, 2, 7, 3],
        [7, 8, 2, 0, 4],
        [3, 7, 2, 0, 8],
        [4, 5, 0, 5, 3]])
tensor([20, 27,  6, 12, 18])
tensor([25, 21, 20, 17])
tensor(6)
tensor(8)


In [87]:
#matrix mult
x3=torch.randint(size=(4,5),low=0,high=10)
x4=torch.randint(size=(5,4),low=0,high=10)
print(torch.matmul(x3,x4))
x5=torch.randint(size=(4,),low=0,high=10)
x6=torch.randint(size=(4,),low=0,high=10)
print(torch.dot(x6,x5))

#transpose
print(torch.transpose(x3,0,1))  #swap 0-th dim with 1-th dim
#similar with torch.det,torch.inverse

tensor([[ 49,  73, 104,  58],
        [ 89, 111, 152, 142],
        [157, 115, 117, 139],
        [ 97,  76,  92, 133]])
tensor(61)
tensor([[9, 9, 4, 1],
        [2, 2, 4, 2],
        [1, 9, 5, 9],
        [5, 7, 8, 6],
        [0, 2, 9, 4]])


In [89]:
#comparisons
x5>x5
#similar for other operations

tensor([False, False, False, False])

Special functions

In [98]:
x7=torch.randint(size=(4,5),low=0,high=10,dtype=torch.float32)
print(x7)
print(torch.log(x3))
print(torch.exp(x3))
print(torch.sqrt(x3))
print(torch.sigmoid(x3))
print(torch.softmax(x7,dim=0))
print(torch.relu(x7))

tensor([[0., 3., 3., 4., 7.],
        [9., 7., 6., 8., 8.],
        [7., 5., 5., 6., 9.],
        [0., 4., 1., 7., 5.]])
tensor([[2.1972, 0.6931, 0.0000, 1.6094,   -inf],
        [2.1972, 0.6931, 2.1972, 1.9459, 0.6931],
        [1.3863, 1.3863, 1.6094, 2.0794, 2.1972],
        [0.0000, 0.6931, 2.1972, 1.7918, 1.3863]])
tensor([[8.1031e+03, 7.3891e+00, 2.7183e+00, 1.4841e+02, 1.0000e+00],
        [8.1031e+03, 7.3891e+00, 8.1031e+03, 1.0966e+03, 7.3891e+00],
        [5.4598e+01, 5.4598e+01, 1.4841e+02, 2.9810e+03, 8.1031e+03],
        [2.7183e+00, 7.3891e+00, 8.1031e+03, 4.0343e+02, 5.4598e+01]])
tensor([[3.0000, 1.4142, 1.0000, 2.2361, 0.0000],
        [3.0000, 1.4142, 3.0000, 2.6458, 1.4142],
        [2.0000, 2.0000, 2.2361, 2.8284, 3.0000],
        [1.0000, 1.4142, 3.0000, 2.4495, 2.0000]])
tensor([[0.9999, 0.8808, 0.7311, 0.9933, 0.5000],
        [0.9999, 0.8808, 0.9999, 0.9991, 0.8808],
        [0.9820, 0.9820, 0.9933, 0.9997, 0.9999],
        [0.7311, 0.8808, 0.9999, 0.9975, 0.982

In-place operations

In [102]:
print(x5)
x5.add_(x6)
print(x5)
#just take a function and put an _ to do inplace operations

tensor([20,  1,  2, 21])
tensor([25,  1,  2, 25])


For copying use clone function, otherwise changes made in original variable also changes the copy

In [109]:
f=d.clone()
f

tensor([1.9000, 2.3000, 4.0000, 5.4000, 6.7000])

Tensors on GPU

In [111]:
torch.cuda.is_available()

True

In [113]:
device=torch.device('cuda')


In [115]:
#creating tensors on gpu
torch.rand((2,3),device=device)


tensor([[0.7766, 0.2933, 0.5100],
        [0.6273, 0.1696, 0.9754]], device='cuda:0')

In [123]:
#moving existing tesnors to GPU
x9=x1.to(device)
x9+2

tensor([[3, 4, 5],
        [6, 7, 8]], device='cuda:0')

Reshaping Tensors

In [130]:
#reshape
a=torch.ones(4,4)
print(a.reshape(2,2,2,2))
#flatten
print(a.flatten())
#permute
b=torch.rand(2,3,4)
b.permute(2,0,1).shape

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


torch.Size([4, 2, 3])

In [132]:
#unsqueeze
x10=torch.rand(266,266,3)
x10.unsqueeze(0).shape

torch.Size([1, 266, 266, 3])

In [133]:
#squeeze
x11=torch.rand(1,50)
x11.squeeze(0).shape

torch.Size([50])

Conversion


In [ ]:
#if var_name is in tensor
#var_name.numpy()
#for the vis-a-vis
#torch.from_numpy(var_name)