In [56]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [57]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [58]:
df.shape

(569, 33)

In [59]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [60]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0],test_size=0.2)

In [61]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [62]:
X_train,y_train


(array([[-0.31663399, -1.29549045, -0.38813358, ..., -1.20616986,
         -1.28381602, -0.99096679],
        [ 1.34940885, -0.09931926,  1.26442861, ...,  0.11248899,
         -0.07411361, -1.01260953],
        [-0.39783608, -0.11583444, -0.4222489 , ..., -0.47730893,
         -0.23397891, -0.6258149 ],
        ...,
        [-0.045027  , -0.86609566, -0.10871289, ..., -0.49194715,
         -1.23602124, -0.91882432],
        [-0.20463111, -0.24323729, -0.23014718, ..., -0.53845396,
         -0.34275324, -0.97820312],
        [-0.48183824,  1.11100781, -0.33696061, ...,  1.62510414,
          2.43923269,  6.87256257]]),
 309    B
 127    M
 362    B
 477    B
 556    B
       ..
 438    B
 289    B
 439    B
 93     B
 9      M
 Name: diagnosis, Length: 455, dtype: object)

In [63]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [64]:
y_train

array([0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,

Numpy arrays to pytorch tensors

In [65]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [66]:
X_train_tensor.shape

torch.Size([455, 30])

In [67]:
y_train_tensor.shape

torch.Size([455])

Defining the Neural Network

In [72]:
class MY_NN():
  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.rand(1,dtype=torch.float64,requires_grad=True)
  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)
    loss=-(y*torch.log(y_pred)+(1-y)*torch.log(1-y_pred)).mean()  #taking the mean here to take the avg of the losses for each value
    return loss


In [93]:
learning_rate=0.3
epochs=30

In [94]:
#training pipeline
#model
model=MY_NN(X_train_tensor)
#print(model.weights)
#loop
for epoch in range(epochs):
  #forward pass
  y_pred=model.forward(X_train_tensor)
  #print(y_pred)

  #calcualte the loss
  loss=model.loss_function(y_pred,y_train_tensor)
  #print(loss.item())
  #backprop
  loss.backward()
  #update the weights
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad
  #zero the gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()
  #to print loss in each epoch
  print(f'Epoch: {epoch+1} , loss: {loss.item()}')



Epoch: 1 , loss: 2.966157477199799
Epoch: 2 , loss: 2.558656499280562
Epoch: 3 , loss: 2.114073825760181
Epoch: 4 , loss: 1.6652010605323662
Epoch: 5 , loss: 1.2953716419509334
Epoch: 6 , loss: 1.0261997256617406
Epoch: 7 , loss: 0.8796318630841097
Epoch: 8 , loss: 0.8223297464987961
Epoch: 9 , loss: 0.7926491313717365
Epoch: 10 , loss: 0.7706166485183332
Epoch: 11 , loss: 0.7532818793652689
Epoch: 12 , loss: 0.7396131779152112
Epoch: 13 , loss: 0.7288213367320393
Epoch: 14 , loss: 0.7202626609880762
Epoch: 15 , loss: 0.7134254540167078
Epoch: 16 , loss: 0.7079113151146003
Epoch: 17 , loss: 0.7034144104403185
Epoch: 18 , loss: 0.6997021824239239
Epoch: 19 , loss: 0.6965988064033458
Epoch: 20 , loss: 0.6939716759425807
Epoch: 21 , loss: 0.691720728496697
Epoch: 22 , loss: 0.6897702199512552
Epoch: 23 , loss: 0.6880624996011346
Epoch: 24 , loss: 0.6865533594509765
Epoch: 25 , loss: 0.6852085902526416
Epoch: 26 , loss: 0.6840014453106322
Epoch: 27 , loss: 0.6829107780709843
Epoch: 28 , lo

In [84]:
print(model.bias)

tensor([0.2813], dtype=torch.float64, requires_grad=True)


In [97]:
#model_evaluation
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.65).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
print(f'Accuracy:{accuracy.item()}')

Accuracy:0.6228070259094238
