In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,101,size=(6,6))

In [3]:
arr

array([[  8,  16,  60,  79,  11,  87],
       [ 86,  75,  87,  85,  60,  27],
       [ 17,  71,  17,  32,  21,   2],
       [ 84,  25,  53,  82,  45,  48],
       [ 44,  58,  44,  67, 100,  77],
       [ 57,  26,  30,  64,  14, 100]], dtype=int32)

In [4]:
arr.sum(axis=0)

array([296, 271, 291, 409, 251, 341])

In [5]:
arr.sum(axis=1)

array([261, 420, 160, 337, 390, 291])

In [6]:
arr.min(axis=0)

array([ 8, 16, 17, 32, 11,  2], dtype=int32)

In [7]:
arr.max(axis=0)

array([ 86,  75,  87,  85, 100, 100], dtype=int32)

In [8]:
arr.max(axis=1)

array([ 87,  87,  71,  84, 100, 100], dtype=int32)

In [9]:
arr.min(axis=1)

array([ 8, 27,  2, 25, 44, 14], dtype=int32)

In [12]:
arr2=np.random.ranf(size=(1000))
print(arr2)

[5.08485048e-01 3.38010462e-01 5.66768538e-01 4.83780020e-01
 6.66401201e-01 2.95750254e-01 1.97783003e-01 4.42338701e-01
 1.69557515e-01 6.99011303e-01 8.90561596e-01 3.51913902e-01
 5.41808718e-01 5.57490013e-01 2.48565876e-01 9.44698895e-01
 8.41768699e-02 6.95216769e-01 1.07139375e-01 6.43152899e-02
 5.12027674e-01 9.74959055e-01 7.42380932e-01 6.91093457e-01
 1.33863506e-01 2.55996679e-01 6.27233485e-01 9.74231952e-01
 7.07460187e-01 2.47037337e-01 1.75993559e-01 6.61747179e-01
 8.30073183e-01 9.84902860e-01 7.48912820e-01 4.38511944e-01
 1.57618914e-01 1.37122467e-01 3.39599137e-01 6.16942538e-01
 2.90316184e-01 1.02040115e-01 4.04548213e-02 6.79613132e-01
 6.39724345e-01 3.76416852e-01 1.17377132e-01 2.44861168e-02
 9.72677560e-01 9.01669418e-01 4.06514738e-01 2.99323243e-01
 3.95767989e-01 7.63736994e-01 3.55655695e-01 9.43786373e-01
 9.45268192e-01 9.70600744e-01 1.16968836e-01 9.93491295e-01
 3.55849476e-01 1.18823350e-01 4.01453488e-01 7.18732841e-01
 9.99376466e-01 2.510070

In [17]:
mean=arr2.sum()/len(arr2)
sd=(arr2-mean)**2
std=np.sqrt(sd.sum()/(len(arr2)-1))
print(mean)
print(std)

0.4943569198684387
0.2932395171109842


In [20]:
arr3=(arr2-mean)/std
print(arr3)

[ 0.04817948 -0.53316981  0.24693677 -0.03606915  0.58670224 -0.67728479
 -1.01137091 -0.17739157 -1.10762495  0.69790861  1.35112989 -0.48575655
  0.16181925  0.21529531 -0.83819209  1.53574791 -1.39878845  0.68496856
 -1.32048214 -1.46652005  0.06026048  1.63894055  0.84580692  0.67090731
 -1.229348   -0.8128517   0.45313322  1.636461    0.72672084 -0.84340468
 -1.08567687  0.57083118  1.14485342  1.67285073  0.86808184 -0.19044151
 -1.14833775 -1.21823435 -0.52775214  0.41803922 -0.69581596 -1.33787154
 -1.54788858  0.63175732  0.49572931 -0.40219705 -1.28556953 -1.60234476
  1.63116024  1.38900958 -0.29955779 -0.66510025 -0.33620616  0.91863497
 -0.47299636  1.53263604  1.53768931  1.62407792 -1.28696189  1.70213885
 -0.47233553 -1.28063766 -0.31681757  0.76516263  1.72220835 -0.82986736
 -0.7248557   0.20773865  1.38191925  1.65096968  0.08874044 -1.03856422
 -0.59096433 -0.94200608 -1.60933799  1.22669817 -0.82984954  0.69447484
  0.95671064 -0.76193659 -1.43082603  1.29576852  0

In [22]:
#since I used sample std, lemme check
arr3.mean()

np.float64(0.0)

In [23]:
arr3.std()

np.float64(0.999499874937461)

In [24]:
print(np.mean(arr2))
print(np.std(arr2))

0.4943569198684387
0.2930928606791502


In [26]:
a = np.random.randint(1, 10, size=(5,3))
b = np.random.randint(1, 10, size=(3,))
print (a,b)
print((a + b).shape)
print(a + b)

[[7 4 8]
 [9 3 6]
 [4 2 2]
 [8 2 9]
 [7 1 8]] [1 9 8]
(5, 3)
[[ 8 13 16]
 [10 12 14]
 [ 5 11 10]
 [ 9 11 17]
 [ 8 10 16]]
